"""adds last_checked_in column

Revision ID: 3e99abb79ee2
Revises: 9b13616ca682
Create Date: 2023-08-24 17:41:53.901514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e99abb79ee2'
down_revision: Union[str, None] = '9b13616ca682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('last_checked_in', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'last_checked_in')
    # ### end Alembic commands ###
